OBJDIR = $(GARFIELD_HOME)/Object
SRCDIR = $(GARFIELD_HOME)/Source
INCDIR = $(GARFIELD_HOME)/Include
HEEDDIR = $(GARFIELD_HOME)/Heed
LIBDIR = $(GARFIELD_HOME)/Library

# Compiler flags
CFLAGS = -Wall -Wextra -Wno-long-long \
	`root-config --cflags` \
	-O3 -fno-common -c \
	-I$(INCDIR) -I$(HEEDDIR)

# Debug flags
# CFLAGS += -g

LDFLAGS = -L$(LIBDIR) -lGarfield
LDFLAGS += `root-config --glibs` -lGeom -lgfortran -lm
# LDFLAGS += -g

RX_Interaction_GEM: RX_Interaction_GEM.C 
	$(CXX) $(CFLAGS) RX_Interaction_GEM.C
	$(CXX) `root-config --cflags` -o RX_Interaction_GEM RX_Interaction_GEM.o $(LDFLAGS)
	rm RX_Interaction_GEM.o
